# Generated by Django 2.2.6 on 2019-12-06 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('team_name', models.CharField(max_length=256, unique=True)),
                ('team_motto', models.TextField()),
                ('contact_no', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=256)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='matchset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('match_location', models.CharField(max_length=200)),
                ('team1', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='one', to='team.team')),
                ('team2', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='two', to='team.team')),
            ],
        ),
    ]
