# Generated by Django 2.2.6 on 2019-12-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20191206_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
