# Generated by Django 2.2.6 on 2019-12-09 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20191208_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='team.team')),
                ('tname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamname', to='team.team')),
            ],
        ),
    ]
