# Generated by Django 2.2.6 on 2019-12-09 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20191209_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='team.team')),
                ('tname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamname', to='team.team')),
            ],
        ),
        migrations.DeleteModel(
            name='member',
        ),
    ]
