# Generated by Django 2.2.6 on 2019-12-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20191209_1150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
